### ISSUE TITLE
paranamer 2.8.1 has a breaking API change

### ISSUE THREAD

**Issue by pjfanning** [paul-hammant/paranamer#47]
I created a PR for jackson-module-scala to upgrade from paranamer 2.8 to 2.8.1 but the compilation failed.

```
[error] /home/runner/work/jackson-module-scala/jackson-module-scala/src/main/scala/com/fasterxml/jackson/module/scala/introspect/JavaParameterIntrospector.scala:25:40: type mismatch;
[error]  found   : java.lang.reflect.Field
[error]  required: java.lang.reflect.Executable
[error]     Try(paranamer.lookupParameterNames(field, false).headOption.getOrElse(None.orNull))
```

I would not have expected a compilation issue with a patch release. If this is a deliberate API change, I can look into trying to adjust the jackson-module-scala code.

Seems related to https://github.com/paul-hammant/paranamer/commit/c5ae8d06124bb4e4b2fe8037c871885def260de9

Is it possible that 2.8.1 is aiming to drop Java 8 support?

**Comment by haster** [comment]
This is a binary incompatibility, meaning that any code which is compiled against paranamer 2.8, can not be run against paranamer 2.8.1 (ie, 2.8.1 is no longer a drop-in replacement for 2.8).

This was introduced in https://github.com/paul-hammant/paranamer/commit/c5ae8d06124bb4e4b2fe8037c871885def260de9

In the case of some libraries, getting them to compile a new release against the new version can be quite a bit of work/can take quite a while. In our case, we use orika mapper, which is practically dead, meaning that we can't upgrade.

As @pfjanning mentioned, this is a breaking API change in a patch version, and according to semver this should be reserved for major versions. Can you roll this back?

**Comment by paul-hammant** [comment]
Wanna go on a call?

**Comment by pjfanning** [comment]
These are 2 Jackson PRs that workaround the binary incompatible changes by doing casts.
* https://github.com/FasterXML/jackson-module-scala/pull/706
* https://github.com/FasterXML/jackson-modules-base/pull/291

Issue is seen with CachingParanamer but I suspect it affects other impls too.

Jackson uses `new CachingParanamer(new BytecodeReadingParanamer())`

**Comment by haster** [comment]
I could do a call if necessary. My working hours are in UTC+1.

So we use paranamer indirectly, through Orika. If I look at Orika's source it goes:

```java
private final Paranamer paranamer = new CachingParanamer(new AdaptiveParanamer(new BytecodeReadingParanamer(),
            new AnnotationParanamer()));

// skip

for (Constructor<?> constructor : resolvedType.getRawType().getConstructors()) {
        String[] names = paranamer.lookupParameterNames(constructor, false);
```
So it is using the method signature from the Paranamer interface.

This is compiled against a version of Paranamer where lookupParameterNames has the signature
```java
java.lang.String[] com.thoughtworks.paranamer.Paranamer.lookupParameterNames(java.lang.reflect.AccessibleObject, boolean)
```

but now in 2.8.1 the signature changed to:

```java
java.lang.String[] com.thoughtworks.paranamer.Paranamer.lookupParameterNames(java.lang.reflect.Executable, boolean)
```

Because the actual parameters (as Orika uses this method) are of type Constructor,<T> which is a subtype of Executor (which is a subtype of AccessibleObject), this is source code compatible (compile time compatible). Somebody could recompile the code using Paranamer (Orika in our case) against Paranamer 2.8.1 without changing any code.

But, since the types (AccessibleObject vs Executable) are actually different, the signature is different, this is _not_ binary compatible (runtime compatible). The code compiled against Paranamer 2.8 is bound to a method of the signature with accessibleobject, and that method doesn't exist in the 2.8.1 version (hence the "Method not found" in our stacktrace).

**Comment by pjfanning** [comment]
The code change is definitely binary incompatible. It is also appearing to be source incompatible - not the 2 PRs that I have linked above. Those PRs need the code changes - the code does not compile if I only change the paranamer jar version.

**Comment by paul-hammant** [comment]
I didn't think anyone other than PicoContainer2 was using it, sorry.  The jar for JDK tries to be compatible with JDK-9's parameters via single class compiled for the later, inserted into the jar that's substantially for JDK-8.

**Comment by paul-hammant** [comment]
CachingParanamer uses AdaptiveParanamer by default, and that has a ctor that tries to be adaptive between JDK9 parameter names, the original Qdox+ASM field-added way and the ASM/bytecode-reading way (came very early on).

Should not blow up if you're running on JDK8, but the price paid was a change of the one the APIs to refer to a parent reflection class. Sorry again

**Comment by paul-hammant** [comment]
JDK8/9 tricks here -> https://github.com/paul-hammant/paranamer/blob/master/paranamer/src/java/com/thoughtworks/paranamer/AdaptiveParanamer.java#L57

**Comment by pjfanning** [comment]
Thanks @paul-hammant. The releases are done. I, personally, wouldn't advocate that you revert. I'd stick with v2.8 but my worry is that Jackson users will get dependency update suggestions in their build tools and apply them without fully testing.
That's why I'm looking to upgrade the paranamer version used in Jackson.

**Comment by pjfanning** [comment]
Just one other observation. Jackson is built with Java 8 but tested with multiple Java versions and paranamer 2.8 works well on the different versions. We even build for some test runs with newer Java versions but the source compatibility flag is set to 1.8.

**Comment by paul-hammant** [comment]
IzPack had a breaking issue for one of their uses with 2.8 from 2015 (via PicoContainer), which started the upgrade.  We originally tried shipping PicoContainer depending on JDK-9 (v 2.8.1), but were asked in another release to be compatible with JDK-8 (v 2.8.2) that requires 

In the end, towards that adaptive goal, Executable had to be used in preference to AccessibleObject. I might be able to try to do a 2.8.3 release that reverts that, and utiliizes it's own casting deeper in the impl.

**Comment by haster** [comment]
We have downgraded Paranamer for now. Since not a lot seems to be happening at Orika, we might be stuck for a while, but we're looking into our options there.

So a revert in a 2.8.3 or something would be preferable for us, at least in the shorter term, since we can keep up with patches then. But we appreciate the difficulties you describe so it's not a huge problem to simply stick with 2.8 for now.

**Comment by paul-hammant** [comment]
Release 2.8.3 done. Not sure how long it takes to sync to https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/

JDK-9 users of Jackson should pass `<parameters>` into their maven-compile-plugin config or equivalent for their build tool.  JDK-8 users do not have that option for the underlying `javac`

**Comment by pjfanning** [comment]
Thanks @paul-hammant - I tried v2.8.3 and it looks to be source compatible with v2.8.

**Comment by haster** [comment]
2.8.3 works for us also, thanks for the quick resolution!

**Comment by paul-hammant** [comment]
You're welcome - sorry for breaking the ABI in a minor release
